### ISSUE TITLE
A lot of code here is copy-pasted from ThingsBoard

### ISSUE THREAD

**Issue by ashvayka** [osswangxining/iotplatform#2]
You need to put a NOTICE about this in the root folder, according to Apache 2.0.

See https://github.com/osswangxining/iotplatform/search?q=ThingsBoard&unscoped_q=ThingsBoard

**Comment by osswangxining** [comment]
Yes it is under readme.md in https://github.com/osswangxining/iotplatform/blob/master/README.md
This project is only for personal experiment and no any commercial support.
